#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyktx
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kytucxa")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertloaiphong(loaiphong instance);
    partial void Updateloaiphong(loaiphong instance);
    partial void Deleteloaiphong(loaiphong instance);
    partial void Inserttang(tang instance);
    partial void Updatetang(tang instance);
    partial void Deletetang(tang instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertphieuthu(phieuthu instance);
    partial void Updatephieuthu(phieuthu instance);
    partial void Deletephieuthu(phieuthu instance);
    partial void Insertphong(phong instance);
    partial void Updatephong(phong instance);
    partial void Deletephong(phong instance);
    partial void Insertquydinh(quydinh instance);
    partial void Updatequydinh(quydinh instance);
    partial void Deletequydinh(quydinh instance);
    partial void Insertsinhvien(sinhvien instance);
    partial void Updatesinhvien(sinhvien instance);
    partial void Deletesinhvien(sinhvien instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::quanlyktx.Properties.Settings.Default.kytucxaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<loaiphong> loaiphongs
		{
			get
			{
				return this.GetTable<loaiphong>();
			}
		}
		
		public System.Data.Linq.Table<tang> tangs
		{
			get
			{
				return this.GetTable<tang>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<phieuthu> phieuthus
		{
			get
			{
				return this.GetTable<phieuthu>();
			}
		}
		
		public System.Data.Linq.Table<phong> phongs
		{
			get
			{
				return this.GetTable<phong>();
			}
		}
		
		public System.Data.Linq.Table<quydinh> quydinhs
		{
			get
			{
				return this.GetTable<quydinh>();
			}
		}
		
		public System.Data.Linq.Table<sinhvien> sinhviens
		{
			get
			{
				return this.GetTable<sinhvien>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nhanvien_delete")]
		public int nhanvien_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string manv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sinhvien_selectid")]
		public ISingleResult<sinhvien_selectidResult> sinhvien_selectid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string masv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), masv);
			return ((ISingleResult<sinhvien_selectidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nhanvien_insert")]
		public int nhanvien_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string manv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string matkhau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string chucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string ghichu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv, hoten, matkhau, chucvu, email, ghichu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nhanvien_selectall")]
		public ISingleResult<nhanvien_selectallResult> nhanvien_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<nhanvien_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nhanvien_update")]
		public int nhanvien_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string manv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string matkhau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string chucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string ghichu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv, hoten, matkhau, chucvu, email, ghichu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sinhvien_delete")]
		public int sinhvien_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string masv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), masv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sinhvien_insert")]
		public int sinhvien_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string masv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hokhau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(5)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaydangky, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string trangthai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string thoigianhoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), masv, hoten, maphong, hokhau, gioitinh, ngaysinh, ngaydangky, trangthai, sdt, thoigianhoc, lop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sinhvien_selectall")]
		public ISingleResult<sinhvien_selectallResult> sinhvien_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sinhvien_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sinhvien_update")]
		public int sinhvien_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string masv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hokhau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(5)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaydangky, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string trangthai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string thoigianhoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), masv, hoten, maphong, hokhau, gioitinh, ngaysinh, ngaydangky, trangthai, sdt, thoigianhoc, lop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nhanvien_selectbyemail")]
		public ISingleResult<nhanvien_selectbyemailResult> nhanvien_selectbyemail([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<nhanvien_selectbyemailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sinhvien_searchbyname")]
		public ISingleResult<sinhvien_searchbynameResult> sinhvien_searchbyname([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hoten);
			return ((ISingleResult<sinhvien_searchbynameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sinhvien_selectbyname")]
		public ISingleResult<sinhvien_selectbynameResult> sinhvien_selectbyname([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hoten);
			return ((ISingleResult<sinhvien_selectbynameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sinhvien_selectbymaphong")]
		public ISingleResult<sinhvien_selectbymaphongResult> sinhvien_selectbymaphong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong);
			return ((ISingleResult<sinhvien_selectbymaphongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.phong_delete")]
		public int phong_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.phong_update")]
		public int phong_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string matang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maloaiphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string slmax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sldango, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sodienthangtruoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sodienthangsau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sonuocthangtruoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sonuocthangsau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sltaisan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tinhtrang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string gioitinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, tenphong, matang, maloaiphong, slmax, sldango, sodienthangtruoc, sodienthangsau, sonuocthangtruoc, sonuocthangsau, sltaisan, tinhtrang, gioitinh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.phong_insert")]
		public int phong_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string matang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maloaiphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string slmax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sldango, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sodienthangtruoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sodienthangsau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sonuocthangtruoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sonuocthangsau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sltaisan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tinhtrang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string gioitinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, tenphong, matang, maloaiphong, slmax, sldango, sodienthangtruoc, sodienthangsau, sonuocthangtruoc, sonuocthangsau, sltaisan, tinhtrang, gioitinh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.phong_searchbytenphong")]
		public ISingleResult<phong_searchbytenphongResult> phong_searchbytenphong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenphong);
			return ((ISingleResult<phong_searchbytenphongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.phong_selectall")]
		public ISingleResult<phong_selectallResult> phong_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<phong_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.phong_selectbymaphong")]
		public ISingleResult<phong_selectbymaphongResult> phong_selectbymaphong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string maphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong);
			return ((ISingleResult<phong_selectbymaphongResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaiphong")]
	public partial class loaiphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maloaiphong;
		
		private string _tenloaiphong;
		
		private string _dongia;
		
		private EntitySet<phong> _phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaiphongChanging(string value);
    partial void OnmaloaiphongChanged();
    partial void OntenloaiphongChanging(string value);
    partial void OntenloaiphongChanged();
    partial void OndongiaChanging(string value);
    partial void OndongiaChanged();
    #endregion
		
		public loaiphong()
		{
			this._phongs = new EntitySet<phong>(new Action<phong>(this.attach_phongs), new Action<phong>(this.detach_phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaiphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maloaiphong
		{
			get
			{
				return this._maloaiphong;
			}
			set
			{
				if ((this._maloaiphong != value))
				{
					this.OnmaloaiphongChanging(value);
					this.SendPropertyChanging();
					this._maloaiphong = value;
					this.SendPropertyChanged("maloaiphong");
					this.OnmaloaiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloaiphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenloaiphong
		{
			get
			{
				return this._tenloaiphong;
			}
			set
			{
				if ((this._tenloaiphong != value))
				{
					this.OntenloaiphongChanging(value);
					this.SendPropertyChanging();
					this._tenloaiphong = value;
					this.SendPropertyChanged("tenloaiphong");
					this.OntenloaiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this.OndongiaChanging(value);
					this.SendPropertyChanging();
					this._dongia = value;
					this.SendPropertyChanged("dongia");
					this.OndongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_phong", Storage="_phongs", ThisKey="maloaiphong", OtherKey="maloaiphong")]
		public EntitySet<phong> phongs
		{
			get
			{
				return this._phongs;
			}
			set
			{
				this._phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = this;
		}
		
		private void detach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tang")]
	public partial class tang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matang;
		
		private string _tentang;
		
		private string _manv;
		
		private string _ghichu;
		
		private EntitySet<phong> _phongs;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatangChanging(string value);
    partial void OnmatangChanged();
    partial void OntentangChanging(string value);
    partial void OntentangChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    #endregion
		
		public tang()
		{
			this._phongs = new EntitySet<phong>(new Action<phong>(this.attach_phongs), new Action<phong>(this.detach_phongs));
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matang", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matang
		{
			get
			{
				return this._matang;
			}
			set
			{
				if ((this._matang != value))
				{
					this.OnmatangChanging(value);
					this.SendPropertyChanging();
					this._matang = value;
					this.SendPropertyChanged("matang");
					this.OnmatangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tentang
		{
			get
			{
				return this._tentang;
			}
			set
			{
				if ((this._tentang != value))
				{
					this.OntentangChanging(value);
					this.SendPropertyChanging();
					this._tentang = value;
					this.SendPropertyChanged("tentang");
					this.OntentangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tang_phong", Storage="_phongs", ThisKey="matang", OtherKey="matang")]
		public EntitySet<phong> phongs
		{
			get
			{
				return this._phongs;
			}
			set
			{
				this._phongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_tang", Storage="_nhanvien", ThisKey="manv", OtherKey="manv", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.tangs.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.tangs.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.tang = this;
		}
		
		private void detach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.tang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manv;
		
		private string _hoten;
		
		private string _matkhau;
		
		private string _chucvu;
		
		private string _email;
		
		private string _ghichu;
		
		private EntitySet<tang> _tangs;
		
		private EntitySet<phieuthu> _phieuthus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnchucvuChanging(string value);
    partial void OnchucvuChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    #endregion
		
		public nhanvien()
		{
			this._tangs = new EntitySet<tang>(new Action<tang>(this.attach_tangs), new Action<tang>(this.detach_tangs));
			this._phieuthus = new EntitySet<phieuthu>(new Action<phieuthu>(this.attach_phieuthus), new Action<phieuthu>(this.detach_phieuthus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucvu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string chucvu
		{
			get
			{
				return this._chucvu;
			}
			set
			{
				if ((this._chucvu != value))
				{
					this.OnchucvuChanging(value);
					this.SendPropertyChanging();
					this._chucvu = value;
					this.SendPropertyChanged("chucvu");
					this.OnchucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_tang", Storage="_tangs", ThisKey="manv", OtherKey="manv")]
		public EntitySet<tang> tangs
		{
			get
			{
				return this._tangs;
			}
			set
			{
				this._tangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_phieuthu", Storage="_phieuthus", ThisKey="manv", OtherKey="manv")]
		public EntitySet<phieuthu> phieuthus
		{
			get
			{
				return this._phieuthus;
			}
			set
			{
				this._phieuthus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tangs(tang entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_tangs(tang entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
		
		private void attach_phieuthus(phieuthu entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_phieuthus(phieuthu entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieuthu")]
	public partial class phieuthu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphieu;
		
		private string _maphong;
		
		private System.DateTime _ngaythu;
		
		private string _sotien;
		
		private string _masv;
		
		private string _manv;
		
		private EntityRef<nhanvien> _nhanvien;
		
		private EntityRef<phong> _phong;
		
		private EntityRef<sinhvien> _sinhvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphieuChanging(string value);
    partial void OnmaphieuChanged();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OnngaythuChanging(System.DateTime value);
    partial void OnngaythuChanged();
    partial void OnsotienChanging(string value);
    partial void OnsotienChanged();
    partial void OnmasvChanging(string value);
    partial void OnmasvChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    #endregion
		
		public phieuthu()
		{
			this._nhanvien = default(EntityRef<nhanvien>);
			this._phong = default(EntityRef<phong>);
			this._sinhvien = default(EntityRef<sinhvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphieu
		{
			get
			{
				return this._maphieu;
			}
			set
			{
				if ((this._maphieu != value))
				{
					this.OnmaphieuChanging(value);
					this.SendPropertyChanging();
					this._maphieu = value;
					this.SendPropertyChanged("maphieu");
					this.OnmaphieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					if (this._phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythu", DbType="DateTime NOT NULL")]
		public System.DateTime ngaythu
		{
			get
			{
				return this._ngaythu;
			}
			set
			{
				if ((this._ngaythu != value))
				{
					this.OnngaythuChanging(value);
					this.SendPropertyChanging();
					this._ngaythu = value;
					this.SendPropertyChanged("ngaythu");
					this.OnngaythuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sotien
		{
			get
			{
				return this._sotien;
			}
			set
			{
				if ((this._sotien != value))
				{
					this.OnsotienChanging(value);
					this.SendPropertyChanging();
					this._sotien = value;
					this.SendPropertyChanged("sotien");
					this.OnsotienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					if (this._sinhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmasvChanging(value);
					this.SendPropertyChanging();
					this._masv = value;
					this.SendPropertyChanged("masv");
					this.OnmasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_phieuthu", Storage="_nhanvien", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.phieuthus.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.phieuthus.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_phieuthu", Storage="_phong", ThisKey="maphong", OtherKey="maphong", IsForeignKey=true)]
		public phong phong
		{
			get
			{
				return this._phong.Entity;
			}
			set
			{
				phong previousValue = this._phong.Entity;
				if (((previousValue != value) 
							|| (this._phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phong.Entity = null;
						previousValue.phieuthus.Remove(this);
					}
					this._phong.Entity = value;
					if ((value != null))
					{
						value.phieuthus.Add(this);
						this._maphong = value.maphong;
					}
					else
					{
						this._maphong = default(string);
					}
					this.SendPropertyChanged("phong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sinhvien_phieuthu", Storage="_sinhvien", ThisKey="masv", OtherKey="masv", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public sinhvien sinhvien
		{
			get
			{
				return this._sinhvien.Entity;
			}
			set
			{
				sinhvien previousValue = this._sinhvien.Entity;
				if (((previousValue != value) 
							|| (this._sinhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sinhvien.Entity = null;
						previousValue.phieuthus.Remove(this);
					}
					this._sinhvien.Entity = value;
					if ((value != null))
					{
						value.phieuthus.Add(this);
						this._masv = value.masv;
					}
					else
					{
						this._masv = default(string);
					}
					this.SendPropertyChanged("sinhvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phong")]
	public partial class phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphong;
		
		private string _tenphong;
		
		private string _matang;
		
		private string _maloaiphong;
		
		private System.Nullable<int> _slmax;
		
		private System.Nullable<int> _sldango;
		
		private System.Nullable<int> _sodienthangtruoc;
		
		private System.Nullable<int> _sodienthangsau;
		
		private System.Nullable<int> _sonuocthangtruoc;
		
		private System.Nullable<int> _sonuocthangsau;
		
		private System.Nullable<int> _sltaisan;
		
		private string _tinhtrang;
		
		private string _gioitinh;
		
		private EntitySet<phieuthu> _phieuthus;
		
		private EntitySet<sinhvien> _sinhviens;
		
		private EntityRef<loaiphong> _loaiphong;
		
		private EntityRef<tang> _tang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OntenphongChanging(string value);
    partial void OntenphongChanged();
    partial void OnmatangChanging(string value);
    partial void OnmatangChanged();
    partial void OnmaloaiphongChanging(string value);
    partial void OnmaloaiphongChanged();
    partial void OnslmaxChanging(System.Nullable<int> value);
    partial void OnslmaxChanged();
    partial void OnsldangoChanging(System.Nullable<int> value);
    partial void OnsldangoChanged();
    partial void OnsodienthangtruocChanging(System.Nullable<int> value);
    partial void OnsodienthangtruocChanged();
    partial void OnsodienthangsauChanging(System.Nullable<int> value);
    partial void OnsodienthangsauChanged();
    partial void OnsonuocthangtruocChanging(System.Nullable<int> value);
    partial void OnsonuocthangtruocChanged();
    partial void OnsonuocthangsauChanging(System.Nullable<int> value);
    partial void OnsonuocthangsauChanged();
    partial void OnsltaisanChanging(System.Nullable<int> value);
    partial void OnsltaisanChanged();
    partial void OntinhtrangChanging(string value);
    partial void OntinhtrangChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    #endregion
		
		public phong()
		{
			this._phieuthus = new EntitySet<phieuthu>(new Action<phieuthu>(this.attach_phieuthus), new Action<phieuthu>(this.detach_phieuthus));
			this._sinhviens = new EntitySet<sinhvien>(new Action<sinhvien>(this.attach_sinhviens), new Action<sinhvien>(this.detach_sinhviens));
			this._loaiphong = default(EntityRef<loaiphong>);
			this._tang = default(EntityRef<tang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenphong", DbType="NVarChar(50)")]
		public string tenphong
		{
			get
			{
				return this._tenphong;
			}
			set
			{
				if ((this._tenphong != value))
				{
					this.OntenphongChanging(value);
					this.SendPropertyChanging();
					this._tenphong = value;
					this.SendPropertyChanged("tenphong");
					this.OntenphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matang", DbType="NVarChar(50)")]
		public string matang
		{
			get
			{
				return this._matang;
			}
			set
			{
				if ((this._matang != value))
				{
					if (this._tang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatangChanging(value);
					this.SendPropertyChanging();
					this._matang = value;
					this.SendPropertyChanged("matang");
					this.OnmatangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaiphong", DbType="NVarChar(50)")]
		public string maloaiphong
		{
			get
			{
				return this._maloaiphong;
			}
			set
			{
				if ((this._maloaiphong != value))
				{
					if (this._loaiphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiphongChanging(value);
					this.SendPropertyChanging();
					this._maloaiphong = value;
					this.SendPropertyChanged("maloaiphong");
					this.OnmaloaiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slmax", DbType="Int")]
		public System.Nullable<int> slmax
		{
			get
			{
				return this._slmax;
			}
			set
			{
				if ((this._slmax != value))
				{
					this.OnslmaxChanging(value);
					this.SendPropertyChanging();
					this._slmax = value;
					this.SendPropertyChanged("slmax");
					this.OnslmaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sldango", DbType="Int")]
		public System.Nullable<int> sldango
		{
			get
			{
				return this._sldango;
			}
			set
			{
				if ((this._sldango != value))
				{
					this.OnsldangoChanging(value);
					this.SendPropertyChanging();
					this._sldango = value;
					this.SendPropertyChanged("sldango");
					this.OnsldangoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthangtruoc", DbType="Int")]
		public System.Nullable<int> sodienthangtruoc
		{
			get
			{
				return this._sodienthangtruoc;
			}
			set
			{
				if ((this._sodienthangtruoc != value))
				{
					this.OnsodienthangtruocChanging(value);
					this.SendPropertyChanging();
					this._sodienthangtruoc = value;
					this.SendPropertyChanged("sodienthangtruoc");
					this.OnsodienthangtruocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthangsau", DbType="Int")]
		public System.Nullable<int> sodienthangsau
		{
			get
			{
				return this._sodienthangsau;
			}
			set
			{
				if ((this._sodienthangsau != value))
				{
					this.OnsodienthangsauChanging(value);
					this.SendPropertyChanging();
					this._sodienthangsau = value;
					this.SendPropertyChanged("sodienthangsau");
					this.OnsodienthangsauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonuocthangtruoc", DbType="Int")]
		public System.Nullable<int> sonuocthangtruoc
		{
			get
			{
				return this._sonuocthangtruoc;
			}
			set
			{
				if ((this._sonuocthangtruoc != value))
				{
					this.OnsonuocthangtruocChanging(value);
					this.SendPropertyChanging();
					this._sonuocthangtruoc = value;
					this.SendPropertyChanged("sonuocthangtruoc");
					this.OnsonuocthangtruocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonuocthangsau", DbType="Int")]
		public System.Nullable<int> sonuocthangsau
		{
			get
			{
				return this._sonuocthangsau;
			}
			set
			{
				if ((this._sonuocthangsau != value))
				{
					this.OnsonuocthangsauChanging(value);
					this.SendPropertyChanging();
					this._sonuocthangsau = value;
					this.SendPropertyChanged("sonuocthangsau");
					this.OnsonuocthangsauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sltaisan", DbType="Int")]
		public System.Nullable<int> sltaisan
		{
			get
			{
				return this._sltaisan;
			}
			set
			{
				if ((this._sltaisan != value))
				{
					this.OnsltaisanChanging(value);
					this.SendPropertyChanging();
					this._sltaisan = value;
					this.SendPropertyChanged("sltaisan");
					this.OnsltaisanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="NVarChar(50)")]
		public string tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_phieuthu", Storage="_phieuthus", ThisKey="maphong", OtherKey="maphong")]
		public EntitySet<phieuthu> phieuthus
		{
			get
			{
				return this._phieuthus;
			}
			set
			{
				this._phieuthus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_sinhvien", Storage="_sinhviens", ThisKey="maphong", OtherKey="maphong")]
		public EntitySet<sinhvien> sinhviens
		{
			get
			{
				return this._sinhviens;
			}
			set
			{
				this._sinhviens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_phong", Storage="_loaiphong", ThisKey="maloaiphong", OtherKey="maloaiphong", IsForeignKey=true, DeleteRule="CASCADE")]
		public loaiphong loaiphong
		{
			get
			{
				return this._loaiphong.Entity;
			}
			set
			{
				loaiphong previousValue = this._loaiphong.Entity;
				if (((previousValue != value) 
							|| (this._loaiphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiphong.Entity = null;
						previousValue.phongs.Remove(this);
					}
					this._loaiphong.Entity = value;
					if ((value != null))
					{
						value.phongs.Add(this);
						this._maloaiphong = value.maloaiphong;
					}
					else
					{
						this._maloaiphong = default(string);
					}
					this.SendPropertyChanged("loaiphong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tang_phong", Storage="_tang", ThisKey="matang", OtherKey="matang", IsForeignKey=true, DeleteRule="CASCADE")]
		public tang tang
		{
			get
			{
				return this._tang.Entity;
			}
			set
			{
				tang previousValue = this._tang.Entity;
				if (((previousValue != value) 
							|| (this._tang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tang.Entity = null;
						previousValue.phongs.Remove(this);
					}
					this._tang.Entity = value;
					if ((value != null))
					{
						value.phongs.Add(this);
						this._matang = value.matang;
					}
					else
					{
						this._matang = default(string);
					}
					this.SendPropertyChanged("tang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieuthus(phieuthu entity)
		{
			this.SendPropertyChanging();
			entity.phong = this;
		}
		
		private void detach_phieuthus(phieuthu entity)
		{
			this.SendPropertyChanging();
			entity.phong = null;
		}
		
		private void attach_sinhviens(sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.phong = this;
		}
		
		private void detach_sinhviens(sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quydinh")]
	public partial class quydinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tiendien;
		
		private string _tiennuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntiendienChanging(string value);
    partial void OntiendienChanged();
    partial void OntiennuocChanging(string value);
    partial void OntiennuocChanged();
    #endregion
		
		public quydinh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiendien", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tiendien
		{
			get
			{
				return this._tiendien;
			}
			set
			{
				if ((this._tiendien != value))
				{
					this.OntiendienChanging(value);
					this.SendPropertyChanging();
					this._tiendien = value;
					this.SendPropertyChanged("tiendien");
					this.OntiendienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiennuoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tiennuoc
		{
			get
			{
				return this._tiennuoc;
			}
			set
			{
				if ((this._tiennuoc != value))
				{
					this.OntiennuocChanging(value);
					this.SendPropertyChanging();
					this._tiennuoc = value;
					this.SendPropertyChanged("tiennuoc");
					this.OntiennuocChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sinhvien")]
	public partial class sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _masv;
		
		private string _hoten;
		
		private string _maphong;
		
		private string _hokhau;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private System.DateTime _ngaydangky;
		
		private string _trangthai;
		
		private int _sdt;
		
		private string _thoigianhoc;
		
		private string _lop;
		
		private EntitySet<phieuthu> _phieuthus;
		
		private EntityRef<phong> _phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasvChanging(string value);
    partial void OnmasvChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OnhokhauChanging(string value);
    partial void OnhokhauChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(System.DateTime value);
    partial void OnngaysinhChanged();
    partial void OnngaydangkyChanging(System.DateTime value);
    partial void OnngaydangkyChanged();
    partial void OntrangthaiChanging(string value);
    partial void OntrangthaiChanged();
    partial void OnsdtChanging(int value);
    partial void OnsdtChanged();
    partial void OnthoigianhocChanging(string value);
    partial void OnthoigianhocChanged();
    partial void OnlopChanging(string value);
    partial void OnlopChanged();
    #endregion
		
		public sinhvien()
		{
			this._phieuthus = new EntitySet<phieuthu>(new Action<phieuthu>(this.attach_phieuthus), new Action<phieuthu>(this.detach_phieuthus));
			this._phong = default(EntityRef<phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					this.OnmasvChanging(value);
					this.SendPropertyChanging();
					this._masv = value;
					this.SendPropertyChanged("masv");
					this.OnmasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					if (this._phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hokhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hokhau
		{
			get
			{
				return this._hokhau;
			}
			set
			{
				if ((this._hokhau != value))
				{
					this.OnhokhauChanging(value);
					this.SendPropertyChanging();
					this._hokhau = value;
					this.SendPropertyChanged("hokhau");
					this.OnhokhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangky", DbType="Date NOT NULL")]
		public System.DateTime ngaydangky
		{
			get
			{
				return this._ngaydangky;
			}
			set
			{
				if ((this._ngaydangky != value))
				{
					this.OnngaydangkyChanging(value);
					this.SendPropertyChanging();
					this._ngaydangky = value;
					this.SendPropertyChanged("ngaydangky");
					this.OnngaydangkyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int NOT NULL")]
		public int sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigianhoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string thoigianhoc
		{
			get
			{
				return this._thoigianhoc;
			}
			set
			{
				if ((this._thoigianhoc != value))
				{
					this.OnthoigianhocChanging(value);
					this.SendPropertyChanging();
					this._thoigianhoc = value;
					this.SendPropertyChanged("thoigianhoc");
					this.OnthoigianhocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this.OnlopChanging(value);
					this.SendPropertyChanging();
					this._lop = value;
					this.SendPropertyChanged("lop");
					this.OnlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sinhvien_phieuthu", Storage="_phieuthus", ThisKey="masv", OtherKey="masv")]
		public EntitySet<phieuthu> phieuthus
		{
			get
			{
				return this._phieuthus;
			}
			set
			{
				this._phieuthus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_sinhvien", Storage="_phong", ThisKey="maphong", OtherKey="maphong", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public phong phong
		{
			get
			{
				return this._phong.Entity;
			}
			set
			{
				phong previousValue = this._phong.Entity;
				if (((previousValue != value) 
							|| (this._phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phong.Entity = null;
						previousValue.sinhviens.Remove(this);
					}
					this._phong.Entity = value;
					if ((value != null))
					{
						value.sinhviens.Add(this);
						this._maphong = value.maphong;
					}
					else
					{
						this._maphong = default(string);
					}
					this.SendPropertyChanged("phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieuthus(phieuthu entity)
		{
			this.SendPropertyChanging();
			entity.sinhvien = this;
		}
		
		private void detach_phieuthus(phieuthu entity)
		{
			this.SendPropertyChanging();
			entity.sinhvien = null;
		}
	}
	
	public partial class sinhvien_selectidResult
	{
		
		private string _masv;
		
		private string _hoten;
		
		private string _maphong;
		
		private string _hokhau;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private System.DateTime _ngaydangky;
		
		private string _trangthai;
		
		private int _sdt;
		
		private string _thoigianhoc;
		
		private string _lop;
		
		public sinhvien_selectidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					this._masv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this._hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hokhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hokhau
		{
			get
			{
				return this._hokhau;
			}
			set
			{
				if ((this._hokhau != value))
				{
					this._hokhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this._ngaysinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangky", DbType="Date NOT NULL")]
		public System.DateTime ngaydangky
		{
			get
			{
				return this._ngaydangky;
			}
			set
			{
				if ((this._ngaydangky != value))
				{
					this._ngaydangky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this._trangthai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int NOT NULL")]
		public int sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this._sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigianhoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string thoigianhoc
		{
			get
			{
				return this._thoigianhoc;
			}
			set
			{
				if ((this._thoigianhoc != value))
				{
					this._thoigianhoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this._lop = value;
				}
			}
		}
	}
	
	public partial class nhanvien_selectallResult
	{
		
		private string _manv;
		
		private string _hoten;
		
		private string _matkhau;
		
		private string _chucvu;
		
		private string _email;
		
		private string _ghichu;
		
		public nhanvien_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this._manv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this._hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this._matkhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucvu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string chucvu
		{
			get
			{
				return this._chucvu;
			}
			set
			{
				if ((this._chucvu != value))
				{
					this._chucvu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this._ghichu = value;
				}
			}
		}
	}
	
	public partial class sinhvien_selectallResult
	{
		
		private string _masv;
		
		private string _hoten;
		
		private string _maphong;
		
		private string _hokhau;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private System.DateTime _ngaydangky;
		
		private string _trangthai;
		
		private int _sdt;
		
		private string _thoigianhoc;
		
		private string _lop;
		
		public sinhvien_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					this._masv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this._hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hokhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hokhau
		{
			get
			{
				return this._hokhau;
			}
			set
			{
				if ((this._hokhau != value))
				{
					this._hokhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this._ngaysinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangky", DbType="Date NOT NULL")]
		public System.DateTime ngaydangky
		{
			get
			{
				return this._ngaydangky;
			}
			set
			{
				if ((this._ngaydangky != value))
				{
					this._ngaydangky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this._trangthai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int NOT NULL")]
		public int sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this._sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigianhoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string thoigianhoc
		{
			get
			{
				return this._thoigianhoc;
			}
			set
			{
				if ((this._thoigianhoc != value))
				{
					this._thoigianhoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this._lop = value;
				}
			}
		}
	}
	
	public partial class nhanvien_selectbyemailResult
	{
		
		private string _manv;
		
		private string _hoten;
		
		private string _matkhau;
		
		private string _chucvu;
		
		private string _email;
		
		private string _ghichu;
		
		public nhanvien_selectbyemailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this._manv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this._hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this._matkhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucvu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string chucvu
		{
			get
			{
				return this._chucvu;
			}
			set
			{
				if ((this._chucvu != value))
				{
					this._chucvu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this._ghichu = value;
				}
			}
		}
	}
	
	public partial class sinhvien_searchbynameResult
	{
		
		private string _masv;
		
		private string _hoten;
		
		private string _maphong;
		
		private string _hokhau;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private System.DateTime _ngaydangky;
		
		private string _trangthai;
		
		private int _sdt;
		
		private string _thoigianhoc;
		
		private string _lop;
		
		public sinhvien_searchbynameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					this._masv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this._hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hokhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hokhau
		{
			get
			{
				return this._hokhau;
			}
			set
			{
				if ((this._hokhau != value))
				{
					this._hokhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this._ngaysinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangky", DbType="Date NOT NULL")]
		public System.DateTime ngaydangky
		{
			get
			{
				return this._ngaydangky;
			}
			set
			{
				if ((this._ngaydangky != value))
				{
					this._ngaydangky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this._trangthai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int NOT NULL")]
		public int sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this._sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigianhoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string thoigianhoc
		{
			get
			{
				return this._thoigianhoc;
			}
			set
			{
				if ((this._thoigianhoc != value))
				{
					this._thoigianhoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this._lop = value;
				}
			}
		}
	}
	
	public partial class sinhvien_selectbynameResult
	{
		
		private string _masv;
		
		private string _hoten;
		
		private string _maphong;
		
		private string _hokhau;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private System.DateTime _ngaydangky;
		
		private string _trangthai;
		
		private int _sdt;
		
		private string _thoigianhoc;
		
		private string _lop;
		
		public sinhvien_selectbynameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					this._masv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this._hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hokhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hokhau
		{
			get
			{
				return this._hokhau;
			}
			set
			{
				if ((this._hokhau != value))
				{
					this._hokhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this._ngaysinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangky", DbType="Date NOT NULL")]
		public System.DateTime ngaydangky
		{
			get
			{
				return this._ngaydangky;
			}
			set
			{
				if ((this._ngaydangky != value))
				{
					this._ngaydangky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this._trangthai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int NOT NULL")]
		public int sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this._sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigianhoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string thoigianhoc
		{
			get
			{
				return this._thoigianhoc;
			}
			set
			{
				if ((this._thoigianhoc != value))
				{
					this._thoigianhoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this._lop = value;
				}
			}
		}
	}
	
	public partial class sinhvien_selectbymaphongResult
	{
		
		private string _masv;
		
		private string _hoten;
		
		private string _maphong;
		
		private string _hokhau;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private System.DateTime _ngaydangky;
		
		private string _trangthai;
		
		private int _sdt;
		
		private string _thoigianhoc;
		
		private string _lop;
		
		public sinhvien_selectbymaphongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					this._masv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this._hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hokhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hokhau
		{
			get
			{
				return this._hokhau;
			}
			set
			{
				if ((this._hokhau != value))
				{
					this._hokhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this._ngaysinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangky", DbType="Date NOT NULL")]
		public System.DateTime ngaydangky
		{
			get
			{
				return this._ngaydangky;
			}
			set
			{
				if ((this._ngaydangky != value))
				{
					this._ngaydangky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this._trangthai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int NOT NULL")]
		public int sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this._sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigianhoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string thoigianhoc
		{
			get
			{
				return this._thoigianhoc;
			}
			set
			{
				if ((this._thoigianhoc != value))
				{
					this._thoigianhoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this._lop = value;
				}
			}
		}
	}
	
	public partial class phong_searchbytenphongResult
	{
		
		private string _maphong;
		
		private string _tenphong;
		
		private string _matang;
		
		private string _maloaiphong;
		
		private int _slmax;
		
		private int _sldango;
		
		private int _sodienthangtruoc;
		
		private int _sodienthangsau;
		
		private int _sonuocthangtruoc;
		
		private int _sonuocthangsau;
		
		private int _sltaisan;
		
		private string _tinhtrang;
		
		private string _gioitinh;
		
		public phong_searchbytenphongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenphong
		{
			get
			{
				return this._tenphong;
			}
			set
			{
				if ((this._tenphong != value))
				{
					this._tenphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string matang
		{
			get
			{
				return this._matang;
			}
			set
			{
				if ((this._matang != value))
				{
					this._matang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaiphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maloaiphong
		{
			get
			{
				return this._maloaiphong;
			}
			set
			{
				if ((this._maloaiphong != value))
				{
					this._maloaiphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slmax", DbType="Int NOT NULL")]
		public int slmax
		{
			get
			{
				return this._slmax;
			}
			set
			{
				if ((this._slmax != value))
				{
					this._slmax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sldango", DbType="Int NOT NULL")]
		public int sldango
		{
			get
			{
				return this._sldango;
			}
			set
			{
				if ((this._sldango != value))
				{
					this._sldango = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthangtruoc", DbType="Int NOT NULL")]
		public int sodienthangtruoc
		{
			get
			{
				return this._sodienthangtruoc;
			}
			set
			{
				if ((this._sodienthangtruoc != value))
				{
					this._sodienthangtruoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthangsau", DbType="Int NOT NULL")]
		public int sodienthangsau
		{
			get
			{
				return this._sodienthangsau;
			}
			set
			{
				if ((this._sodienthangsau != value))
				{
					this._sodienthangsau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonuocthangtruoc", DbType="Int NOT NULL")]
		public int sonuocthangtruoc
		{
			get
			{
				return this._sonuocthangtruoc;
			}
			set
			{
				if ((this._sonuocthangtruoc != value))
				{
					this._sonuocthangtruoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonuocthangsau", DbType="Int NOT NULL")]
		public int sonuocthangsau
		{
			get
			{
				return this._sonuocthangsau;
			}
			set
			{
				if ((this._sonuocthangsau != value))
				{
					this._sonuocthangsau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sltaisan", DbType="Int NOT NULL")]
		public int sltaisan
		{
			get
			{
				return this._sltaisan;
			}
			set
			{
				if ((this._sltaisan != value))
				{
					this._sltaisan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this._tinhtrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
				}
			}
		}
	}
	
	public partial class phong_selectallResult
	{
		
		private string _maphong;
		
		private string _tenphong;
		
		private string _matang;
		
		private string _maloaiphong;
		
		private int _slmax;
		
		private int _sldango;
		
		private int _sodienthangtruoc;
		
		private int _sodienthangsau;
		
		private int _sonuocthangtruoc;
		
		private int _sonuocthangsau;
		
		private int _sltaisan;
		
		private string _tinhtrang;
		
		private string _gioitinh;
		
		public phong_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenphong
		{
			get
			{
				return this._tenphong;
			}
			set
			{
				if ((this._tenphong != value))
				{
					this._tenphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string matang
		{
			get
			{
				return this._matang;
			}
			set
			{
				if ((this._matang != value))
				{
					this._matang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaiphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maloaiphong
		{
			get
			{
				return this._maloaiphong;
			}
			set
			{
				if ((this._maloaiphong != value))
				{
					this._maloaiphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slmax", DbType="Int NOT NULL")]
		public int slmax
		{
			get
			{
				return this._slmax;
			}
			set
			{
				if ((this._slmax != value))
				{
					this._slmax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sldango", DbType="Int NOT NULL")]
		public int sldango
		{
			get
			{
				return this._sldango;
			}
			set
			{
				if ((this._sldango != value))
				{
					this._sldango = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthangtruoc", DbType="Int NOT NULL")]
		public int sodienthangtruoc
		{
			get
			{
				return this._sodienthangtruoc;
			}
			set
			{
				if ((this._sodienthangtruoc != value))
				{
					this._sodienthangtruoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthangsau", DbType="Int NOT NULL")]
		public int sodienthangsau
		{
			get
			{
				return this._sodienthangsau;
			}
			set
			{
				if ((this._sodienthangsau != value))
				{
					this._sodienthangsau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonuocthangtruoc", DbType="Int NOT NULL")]
		public int sonuocthangtruoc
		{
			get
			{
				return this._sonuocthangtruoc;
			}
			set
			{
				if ((this._sonuocthangtruoc != value))
				{
					this._sonuocthangtruoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonuocthangsau", DbType="Int NOT NULL")]
		public int sonuocthangsau
		{
			get
			{
				return this._sonuocthangsau;
			}
			set
			{
				if ((this._sonuocthangsau != value))
				{
					this._sonuocthangsau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sltaisan", DbType="Int NOT NULL")]
		public int sltaisan
		{
			get
			{
				return this._sltaisan;
			}
			set
			{
				if ((this._sltaisan != value))
				{
					this._sltaisan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this._tinhtrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
				}
			}
		}
	}
	
	public partial class phong_selectbymaphongResult
	{
		
		private string _maphong;
		
		private string _tenphong;
		
		private string _matang;
		
		private string _maloaiphong;
		
		private int _slmax;
		
		private int _sldango;
		
		private int _sodienthangtruoc;
		
		private int _sodienthangsau;
		
		private int _sonuocthangtruoc;
		
		private int _sonuocthangsau;
		
		private int _sltaisan;
		
		private string _tinhtrang;
		
		private string _gioitinh;
		
		public phong_selectbymaphongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenphong
		{
			get
			{
				return this._tenphong;
			}
			set
			{
				if ((this._tenphong != value))
				{
					this._tenphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string matang
		{
			get
			{
				return this._matang;
			}
			set
			{
				if ((this._matang != value))
				{
					this._matang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaiphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maloaiphong
		{
			get
			{
				return this._maloaiphong;
			}
			set
			{
				if ((this._maloaiphong != value))
				{
					this._maloaiphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slmax", DbType="Int NOT NULL")]
		public int slmax
		{
			get
			{
				return this._slmax;
			}
			set
			{
				if ((this._slmax != value))
				{
					this._slmax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sldango", DbType="Int NOT NULL")]
		public int sldango
		{
			get
			{
				return this._sldango;
			}
			set
			{
				if ((this._sldango != value))
				{
					this._sldango = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthangtruoc", DbType="Int NOT NULL")]
		public int sodienthangtruoc
		{
			get
			{
				return this._sodienthangtruoc;
			}
			set
			{
				if ((this._sodienthangtruoc != value))
				{
					this._sodienthangtruoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthangsau", DbType="Int NOT NULL")]
		public int sodienthangsau
		{
			get
			{
				return this._sodienthangsau;
			}
			set
			{
				if ((this._sodienthangsau != value))
				{
					this._sodienthangsau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonuocthangtruoc", DbType="Int NOT NULL")]
		public int sonuocthangtruoc
		{
			get
			{
				return this._sonuocthangtruoc;
			}
			set
			{
				if ((this._sonuocthangtruoc != value))
				{
					this._sonuocthangtruoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonuocthangsau", DbType="Int NOT NULL")]
		public int sonuocthangsau
		{
			get
			{
				return this._sonuocthangsau;
			}
			set
			{
				if ((this._sonuocthangsau != value))
				{
					this._sonuocthangsau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sltaisan", DbType="Int NOT NULL")]
		public int sltaisan
		{
			get
			{
				return this._sltaisan;
			}
			set
			{
				if ((this._sltaisan != value))
				{
					this._sltaisan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this._tinhtrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
